Models/Appointment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AliMosaclinicTask.Models
{
    [Table("Appointments")]
    public class Appointment
    {
        public int ID { get; set; }

        [Required, MaxLength(150)]
        [Display(Name = "Patient Name")]
        public string PatientName { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Patient BirthDate")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString ="{0:dd/MMMM/yyy}")]
        public DateTime PatientBirthDate { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Patient Appointment")]
        public DateTime AppointmentDate { get; set; }

        public int DoctorID { get; set; }
        [ForeignKey("DoctorID")]
        public Doctor? Doctor { get; set; }

    }
}

Models/Doctor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AliMosaclinicTask.Models
{
    [Table("Doctors")]
    public class Doctor
    {
        public int ID { get; set; }

        [Required, MaxLength(150)]
        [Display(Name = "Doctor Name")]
        public string DoctorName { get; set; } = string.Empty;

        [Required, MaxLength(500)]
        [Display(Name = "Doctor Schedule")]
        public string DoctorSchedule { get; set; } = string.Empty;
        public virtual List<Appointment>? Appointments { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace AliMosaclinicTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/AppointmentSearchVM.cs
using System.ComponentModel.DataAnnotations;

namespace AliMosaclinicTask.ViewModels
{
    public class AppointmentSearchVM
    {
        [Required]
        public int ID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Patient Appointment")]
        public DateTime AppointmentStartDate { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Patient Appointment")]
        public DateTime AppointmentEndDate { get; set; }
    }
}

Controllers/AppointmentController.cs
using AliMosaclinicTask.Data;
using AliMosaclinicTask.Models;
using AliMosaclinicTask.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace AliMosaclinicTask.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _ToastNotification;
        public AppointmentController(ApplicationDbContext context, IToastNotification ToastNotification)
        {
            _context = context;
            _ToastNotification = ToastNotification;
        }
        public IActionResult Index()
        {
            var data = _context.Appointments.Include(x => x.Doctor).ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.DoctorsList = _context.Doctors.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Appointment model)
        {
            if (ModelState.IsValid)
            {
                _context.Appointments.Add(model);
                _context.SaveChanges();
                _ToastNotification.AddSuccessToastMessage("Appointment added successfully !");
                return RedirectToAction("Index");
            }
            ViewBag.DoctorsList = _context.Doctors.ToList();
            return View();
        }

        public IActionResult Edit(int? id)
        {
            ViewBag.DoctorsList = _context.Doctors.ToList();
            var result = _context.Appointments.FirstOrDefault(x => x.ID == id);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Appointment model)
        {
            
            if (ModelState.IsValid)
            {
                _context.Appointments.Update(model);
                _context.SaveChanges();
                _ToastNotification.AddAlertToastMessage("Appointment edited successfully !");
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentsList = _context.Doctors.ToList();
            return View(model);
        }

        //ajax delete Action
        public IActionResult Delete(int id)
        {
            Appointment? appointment = _context.Appointments.Find(id);
            if (appointment != null)
            {
                _context.Appointments.Remove(appointment);
                _context.SaveChanges();
            }

            return Ok();
        }

        public IActionResult AppointmentPerDoctor(int id)
        {
            var today = DateTime.Today;
            var data = _context.Appointments.Include(x => x.Doctor).Where(x=>x.DoctorID==id&&x.AppointmentDate.Date==today).ToList();
            ViewBag.DoctorID = id;
            return View(data);
        }

        public IActionResult Search(AppointmentSearchVM model)
        {
            ViewBag.DoctorID = model.ID;
            
            var data = _context.Appointments.Include(x => x.Doctor).
               Where(x => x.AppointmentDate.Date >= model.AppointmentStartDate && x.AppointmentDate.Date <= model.AppointmentEndDate && x.DoctorID == model.ID).ToList();
            return View(data);
        }

        

    }
}

Controllers/DoctorController.cs
using AliMosaclinicTask.Data;
using AliMosaclinicTask.Models;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace AliMosaclinicTask.Controllers
{
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _ToastNotification;
        public DoctorController(ApplicationDbContext context, IToastNotification ToastNotification)
        {
            _context = context;
            _ToastNotification = ToastNotification;
        }

        public IActionResult Index()
        {
            return View(_context.Doctors.ToList());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Doctor model)
        {
            if (ModelState.IsValid)
            {
                _context.Doctors.Add(model);
                _context.SaveChanges();
                _ToastNotification.AddSuccessToastMessage("Appointment added successfully !");
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            
            var result = _context.Doctors.FirstOrDefault(x => x.ID == id);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Doctor model)
        {

            if (ModelState.IsValid)
            {
                _context.Doctors.Update(model);
                _context.SaveChanges();
                _ToastNotification.AddAlertToastMessage("Appointment edited successfully !");
                return RedirectToAction("Index");
            }
            
            return View(model);
        }

        //ajax delete Action
        public IActionResult Delete(int id)
        {
            Doctor? doctor = _context.Doctors.Find(id);
            if (doctor != null)
            {
                _context.Doctors.Remove(doctor);
                _context.SaveChanges();
            }

            return Ok();
        }
    }
}

Controllers/HomeController.cs
using AliMosaclinicTask.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AliMosaclinicTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Appointment/Add.cshtml
@model AliMosaclinicTask.Models.Appointment
@{
    ViewData["Title"] = "Add Appointment";
    Layout = "_Admin";
}

<h4>Create Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-4">
                <label asp-for="PatientName" class="control-label"></label>
                <input asp-for="PatientName" class="form-control" />
                <span asp-validation-for="PatientName" class="text-danger"></span>
            </div>
            
            <div class="form-group mt-4">
                <label asp-for="PatientBirthDate" class="control-label"></label>
                <input asp-for="PatientBirthDate" class="form-control" />
                <span asp-validation-for="PatientBirthDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="AppointmentDate" class="control-label"></label>
                <input asp-for="AppointmentDate" class="form-control" />
                <span asp-validation-for="AppointmentDate" class="text-danger"></span>
            </div>
            
            <div class="form-group mt-4">
                <label asp-for="DoctorID" class="control-label"></label>
                <select asp-for="DoctorID" class ="form-control" 
                        asp-items="@(new SelectList(ViewBag.DoctorsList,"ID","DoctorName"))">
                        <option value="0"> Select Doctor For Appointment.....</option>
                </select>
            </div>
            <div class="form-group  mt-4">
                <input type="submit" value="add" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Appointment/AppointmentPerDoctor.cshtml
@model IEnumerable<Appointment>

@{
    ViewData["Title"] = "My Appointments";
    Layout = "_Admin";
}


<div class="row">
    <div class="col-md-12">
        <form asp-controller="Appointment"  asp-action="Search" class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mt-4 col-md-12"><input type="number" id="ID" name="ID" value="@ViewBag.DoctorID" hidden/></div>
            
            <div class="form-group mt-4 col-md-6">
                <label class="control-label">Appointment Start Date</label>
                <input required type="date" id="AppointmentStartDate" name="AppointmentStartDate"  class="form-control" />
                <span for="AppointmentStartDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-4 col-md-6">
                <label  class="control-label">Appointment End Date</label>
                <input required type="date"id="AppointmentEndDate" name="AppointmentEndDate" class="form-control" />
                <span for="AppointmentEndDate" class="text-danger"></span>
            </div>
            <div class="form-group  mt-1 mb-4">
                <input type="submit" value="Search" class="btn btn-primary btn-sm "style="width: 170px;" />
            </div>
        </form>
    </div>
</div>


<table class="table" id="tblStudent">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.PatientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatientBirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th>
                Doctor
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
           
            <td>
                @item.PatientName
            </td>
            <td>
                @item.PatientBirthDate.ToString("dd-MMMM-yyyy")
            </td>
            <td>
                @item.AppointmentDate.ToString("dd-MMMM-yyyy H:mm tt")
            </td>
            <td>
                @item.Doctor.DoctorName
            </td>
            <td></td>
        </tr>
        }
    </tbody>
</table>

Views/Appointment/Edit.cshtml
@model AliMosaclinicTask.Models.Appointment
@{
    ViewData["Title"] = "Add Appointment";
    Layout = "_Admin";
}

<h4>Edit Appointment For @Model.PatientName</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-4">
                <label asp-for="PatientName" class="control-label"></label>
                <input asp-for="PatientName" class="form-control" />
                <span asp-validation-for="PatientName" class="text-danger"></span>
            </div>
            
            <div class="form-group mt-4">
                <label asp-for="PatientBirthDate" class="control-label"></label>
                <input asp-for="PatientBirthDate" class="form-control" />
                <span asp-validation-for="PatientBirthDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="AppointmentDate" class="control-label"></label>
                <input asp-for="AppointmentDate" class="form-control" />
                <span asp-validation-for="AppointmentDate" class="text-danger"></span>
            </div>
            
            <div class="form-group mt-4">
                <label asp-for="DoctorID" class="control-label"></label>
                <select asp-for="DoctorID" class ="form-control" 
                        asp-items="@(new SelectList(ViewBag.DoctorsList,"ID","DoctorName"))">
                        <option value="0"> Select Doctor For Appointment.....</option>
                </select>
            </div>
            <div class="form-group  mt-4">
                <input type="submit" value="Edit" class="btn btn-warning text-light btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Appointment/Index.cshtml
@model IEnumerable<Appointment>

@{
    ViewData["Title"] = "Appointments";
    Layout = "_Admin";
}


<p>
    <a asp-action="Add" class="btn btn-success btn-sm">Create New</a>
</p>

<table class="table" id="tblStudent">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.PatientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatientBirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th>
                Doctor
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
         <tr class="Item-row">
           
            <td>
                @item.PatientName
            </td>
            <td>
                @item.PatientBirthDate.ToString("dd-MMMM-yyyy")
            </td>
            <td>
                @item.AppointmentDate.ToString("dd-MMMM-yyyy H:mm tt")
            </td>
            <td>
                @item.Doctor.DoctorName
            </td>
            <td>
                <a class="btn btn-sm btn-warning text-light" asp-controller="Appointment" asp-action="edit" asp-route-id="@item.ID" >Edit</a> ||
                <a href="javascript:;" class="btn btn-sm btn-danger text-light js-delete" data-id="@item.ID" data-controller="Appointment">Delete</a> 
            </td>
        </tr>
        }
    </tbody>
</table>


@section Scripts{
    <script src="~/js/AjaxDelete.js"></script>
}

Views/Appointment/Search.cshtml
@model IEnumerable<Appointment>

@{
    ViewData["Title"] = "My Appointments";
    Layout = "_Admin";
}


<div class="row">
    <div class="col-md-12">
        <form asp-controller="Appointment"  asp-action="Search" class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mt-4 col-md-12"><input type="number" id="ID" name="ID" value="@ViewBag.DoctorID" hidden/></div>
            
            <div class="form-group mt-4 col-md-6">
                <label class="control-label">Appointment Start Date</label>
                <input required type="date" id="AppointmentStartDate" name="AppointmentStartDate"  class="form-control" />
                <span for="AppointmentStartDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-4 col-md-6">
                <label  class="control-label">Appointment End Date</label>
                <input required type="date"id="AppointmentEndDate" name="AppointmentEndDate" class="form-control" />
                <span for="AppointmentEndDate" class="text-danger"></span>
            </div>
            <div class="form-group  mt-1 mb-4">
                <input type="submit" value="Search" class="btn btn-primary btn-sm "style="width: 170px;" />
            </div>
        </form>
    </div>
</div>


<table class="table" id="tblStudent">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.PatientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatientBirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th>
                Doctor
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
           
            <td>
                @item.PatientName
            </td>
            <td>
                @item.PatientBirthDate.ToString("dd-MMMM-yyyy")
            </td>
            <td>
                @item.AppointmentDate.ToString("dd-MMMM-yyyy H:mm tt")
            </td>
            <td>
                @item.Doctor.DoctorName
            </td>
            <td></td>
        </tr>
        }
    </tbody>
</table>

Views/Doctor/Add.cshtml
@model AliMosaclinicTask.Models.Doctor
@{
    ViewData["Title"] = "Add Doctor";
    Layout = "_Admin";
}

<h4>Create Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-4">
                <label asp-for="DoctorName" class="control-label"></label>
                <input asp-for="DoctorName" class="form-control" />
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            
            <div class="form-group mt-4">
                <label asp-for="DoctorSchedule" class="control-label"></label>
                <input asp-for="DoctorSchedule" class="form-control" />
                <span asp-validation-for="DoctorSchedule" class="text-danger"></span>
            </div>
            
            <div class="form-group  mt-4">
                <input type="submit" value="add" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Doctor/Edit.cshtml
@model AliMosaclinicTask.Models.Doctor
@{
    ViewData["Title"] = "Edit Doctor";
    Layout = "_Admin";
}

<h4>Edit Doctor @Model.DoctorName</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-4">
                <label asp-for="DoctorName" class="control-label"></label>
                <input asp-for="DoctorName" class="form-control" />
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            
            <div class="form-group mt-4">
                <label asp-for="DoctorSchedule" class="control-label"></label>
                <input asp-for="DoctorSchedule" class="form-control" />
                <span asp-validation-for="DoctorSchedule" class="text-danger"></span>
            </div>
            
            <div class="form-group  mt-4">
                <input type="submit" value="Edit" class="btn btn-warning text-light btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Doctor/Index.cshtml
@model IEnumerable<Doctor>

@{
    ViewData["Title"] = "Doctors";
    Layout = "_Admin";
}

<p>
    <a asp-action="Add" class="btn btn-success btn-sm">Create New</a>
</p>

<table class="table" id="tblStudent">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.DoctorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorSchedule)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
         <tr class="Item-row">
            <td>
                @item.DoctorName
            </td>
            <td>
                @item.DoctorSchedule
            </td>
            
            <td>
                <a class="btn btn-sm btn-warning text-light" asp-controller="Doctor" asp-action="edit" asp-route-id="@item.ID" >Edit</a> ||
                <a href="javascript:;" class="btn btn-sm btn-danger text-light js-delete" data-id="@item.ID" data-controller="Doctor">Delete</a> 
            </td>
        </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script src="~/js/AjaxDelete.js"></script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>@ViewData["Title"] - Clinic Dashboard </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="~/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">Clinic</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

   

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        

        

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#">
            <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

        
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#Doctor-nav" data-bs-toggle="collapse" href="#" >
          <i class="bi bi-layout-text-window-reverse"></i><span>Doctors</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="Doctor-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a asp-area="" asp-controller="Doctor" asp-action="Index">
              <i class="bi bi-circle"></i><span>All Doctors</span>
            </a>
          </li>
          <li>
            <a asp-area="" asp-controller="Doctor" asp-action="Add">
              <i class="bi bi-circle"></i><span>Add Doctor</span>
            </a>
          </li>
        </ul>
      </li><!-- End Tables Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#Appointment-nav" data-bs-toggle="collapse" href="#" >
          <i class="bi bi-layout-text-window-reverse"></i><span>Secretary</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="Appointment-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a asp-area="" asp-controller="Appointment" asp-action="Index">
              <i class="bi bi-circle"></i><span>All Appointments</span>
            </a>
          </li>
          <li>
            <a asp-area="" asp-controller="Appointment" asp-action="Add">
              <i class="bi bi-circle"></i><span>Add Appointment</span>
            </a>
          </li>
          
        </ul>
      </li><!-- End Tables Nav -->



      <li class="nav-heading">Pages</li>




      <li class="nav-item">
        <a class="nav-link" asp-controller="Appointment" asp-action="AppointmentPerDoctor" asp-route-id="1">
          <i class="bi bi-file-earmark"></i>
          <span>View As Doctor</span>
        </a>
      </li><!-- End Blank Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">

   <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>Clinic</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.min.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js" ></script>
   @await RenderSectionAsync("Scripts", required: false)
   @await Component.InvokeAsync("NToastNotify")

</body>

</html>